version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myApp

hooks:
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 20
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 60
      runas: ubuntu