name: build-deploy

on:
  pull_request:
    branches: [ a6-demo ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name : Install AWS CLI
        run: |
          python --version
          cat /etc/issue
          sudo apt-get update -y
          sudo apt-get install -y python-pip
          sudo pip install awscli pyrsistent==0.16.0

      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}