name: build-deploy

on:
  push:
    branches: [ a9-demo ]

jobs:

  deploy:
    name: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name : Install AWS CLI
        run: |
          python --version
          cat /etc/issue
          sudo apt-get update -y
          sudo apt-get install -y python-pip
          sudo pip install awscli pyrsistent==0.16.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build JAR
        run: |
          cd cloudwebapp
          mvn clean package
          pwd
          ls -al
          ls -al target/
      - name: Build Deployment Artifact
        run: |
          sudo chmod +x codedeploy/*.sh
          mkdir codedeploy_artifact
          cd codedeploy_artifact
          ls -al
          cd ..
          pwd
          ls -al
          sudo cp appspec.yml codedeploy_artifact/
          sudo cp -r codedeploy codedeploy_artifact/
          sudo cp ./cloudwebapp/target/ROOT.jar codedeploy_artifact/
          sudo cp cloudwatch-config.json codedeploy_artifact/
          pwd
          cd codedeploy_artifact
          pwd
          ls -al
          cd ..
          pwd
          ls -al
      - name: Copy to S3
        run: |
          aws deploy push \
          --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
          --description "This is a new revision for the application" \
          --ignore-hidden-files \
          --s3-location s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}/csye6225-webapp-${{ github.run_number }}.zip \
          --source ./codedeploy_artifact/
      - name: Deploy Application To Codedeploy
        run: |
          output=$(aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ secrets.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME }} \
            --description "CSYE-6225 - CodeDeploy" \
            --region ${{ secrets.AWS_REGION }} \
            --s3-location bucket=${{ secrets.S3_CODEDEPLOY_BUCKET }},key=csye6225-webapp-${{ github.run_number }}.zip,bundleType=zip \
            --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')

          aws deploy wait deployment-successful --deployment-id $dId