name: build-deploy

on:
  pull_request:
    branches: [ a6-demo ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name : Install AWS CLI
        run: |
          python --version
          cat /etc/issue
          sudo apt-get update -y
          sudo apt-get install -y python-pip
          sudo pip install awscli pyrsistent==0.16.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CODEDEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CODEDEPLOY }}
          aws-region: ${{ secrets.AWS_REGION_CODEDEPLOY }}

      - name: Build the jar file for the webapp
        run: |
          cd cloudwebapp
          mvn clean package
          pwd
          ls -al
          ls -al target/
      - name: Build Deployment Artifact
        run: |
          sudo chmod +x codedeploy/*.sh
          mkdir codedeploy_artifact
          cd codedeploy_artifact
          ls -al
          cd ..
          pwd
          ls -al
          sudo cp appspec.yml codedeploy_artifact/
          sudo cp -r codedeploy codedeploy_artifact/
          sudo cp ./cloudwebapp/target/ROOT.jar codedeploy_artifact/
          pwd
          cd codedeploy_artifact
          pwd
          ls -al
          cd ..
          pwd
          ls -al